baseURL: ""
languageCode: "en-us"
title: "Vadiraj Raghavendra Adabaddi"
theme: hugo-profile

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 0

    # Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Vadiraj Raghavendra Adabaddi"
  description: My Portfolio Site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/v-letter.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Vadiraj Adabaddi"
    subtitle: "Tech Enthusiast"
    content: "Currently I am working as an Automation Engineer at Capgemini. I have completed my BE in Electronics & Communication Engineering from BMSIT Bangalore in 2021. I do Data Analysis and Machine Learning projects for fun."
    image: /images/profile photo.jpg
    button:
      enable: false
      name: "Resume"
      url: ""
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Vadiraj-13
        

  # About
  about:
    enable: false
    title: "About Me"
    content: |-
      # I am working as an Automation Engineer at Capgemini. Along with automation testing, I have built a portfolio in Big Data and Data Science technologies. I have completed my  BE in Electronics & Communication Engineering from BMSIT Bangalore.
      # I am working on a project that focuses on web automation using selenium with python and behave.
      # I have basic understanding of Azure.
      # Apart from testing, I am also interested in Data Science and Machine Learning.
    skills:
      enable: True
      title: "Here are a few tools and technologies I've worked with:"
      items:
        - "Python"
        - "Selenium"
        - "behave"
        - "JIRA"
        - "Jupyter Notebook"
        - "Pycharm"
        - "Git"
        - "Github"



  # Experience
  experience:
    enable: true
    items:
      - job: "Automation Engineer"
        company: "Capgemini"
        #companyUrl: "None"
        date: "Sep 2021 - Present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: |
          - Developed automated solutions using python to reduce manual intervention.
          - Achieved certifications in automation.


      # - job: "Software Developer"
      #   company: "Amazon"
      #   companyUrl: "https://example.com"
      #   date: "Sep 2020 - Dec 2021"
      #   featuredLink:
      #     enable: true
      #     url: "https://example.com"
      #   info:
      #     enable: true
      #     content: I worked as a software developer for more than one year in Amazon.
      #   content: |
      #     I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

      #     - Lead backend developer for a product.
      #     - Created a frontend design for a product.

      # - job: "Junior Software Developer"
      #   company: "Apple"
      #   companyUrl: "https://example.com"
      #   date: "Jan 2020 - Aug 2020"
      #   info:
      #     enable: false
      #   featuredLink:
      #     enable: true
      #     url: "https://example.com"
      #   content: |
      #     I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

      #     - Lead backend developer for a product.
      #     - Created a frontend design for a product.

      # - job: "UI/UX Designer"
      #   company: "Netflix"
      #   companyUrl: "https://example.com"
      #   date: "June 2017 - Nov 2019"
      #   featuredLink:
      #     enable: true
      #     url: "https://example.com"
      #   content: |
      #     I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

      #     - Lead backend developer for a product.
      #     - Created a frontend design for a product.

      # - job: "Product Designer"
      #   company: "Google"
      #   companyUrl: "https://example.com"
      #   date: "Feb 2016 - Mar 2017"
      #   content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Bachelor of Engineering"
        school:
          name: "BMS Institute of Technology, Bangalore"
          #url: "https://example.org"
        date: "2017 - 2021"
        GPA: "8.81 out of 10"
        content: |-
          - I Published a paper in "ELSEVIER-SSRN Digital Library" which was successfully presented at the 2nd International Conference on IoT Based Control Networks and Intelligent Systems ICICNIS 2021.
          -- [*Virtual reality and animation are used to teach digital electronics lab, modelled in Blender*](https://dx.doi.org/10.2139/ssrn.3883251)
          - Won awards for projects done during the Project Based Learning (PBL) competitions
          - Achieved "Silver+Elite" Certification in "Interpersonal Skills" exam conducted by NPTEL

      - title: "Class 12"
        school:
          name: "M.E.S Prof  B.R Subba Rao  Pre-University College"
        date: "2016 - 2017"
        content: |-
            - Second rank to the college by securing a percentage 95.3 in the annual board exams
            - Scholarship for "Commitment to Science" and recognized as "The Amateur Scientist" by PESIT in 2016

            Extracurricular Activities
             - Won a prize in sanskrit tounge twister competition held during college fest.
             - Won a prize in kannada essay writing competition
        
      - title: "Class 10"
        school:
          name: "Poornaprajna High School"
          #url: "https://example.org"
        date: "2014 - 2015"
        content: |-
            - Received “Best All Rounder” award for achieving excellence in both sports and academics
            - Secured a percentage of 95.2 in the annual board exams
            - Received Sports Championship award in high school and primary school almost every year




        # featuredLink:
        #   enable: true
        #   name: "My academic record"
        #   url: "https://example.com"
      # - title: "High School"
      #   school:
      #     name: "Thomas Jefferson High School for Science and Technology."
      #     url: "https://example.org"
      #   GPA: "4.2 out of 5.0"
      #   featuredLink:
      #     enable: true
      #     url: "https://example.com"

  
  achievements:
    enable: false
    items:
      
      - title: Achieved AZ-900 Azure Fundemenatal
        #content: Developed a product using Artificial Intelligence.
      - title:  
        #content: Developed a theme and getting 1K+ downloads per month.
        #url: "https://github.com/gurusabarish/hugo-profile"
      - title: Second rank to the college in 2nd PUC annual exam
        #content: We are developed a product which can help others.
      - title: Silver+Elite Certification in "Interpersonal Skills" by NPTEL
        #content: Contributed to a open source project.
        #url: https://example.com

      - title: Scholarship for "Commitment to Science" and recognized as "The Amateur Scientist" by PESIT in 2016
        #content: I solved all problems with optimal solution.
        #url: https://example.com

  # projects
  projects:
    enable: true
    items:
      # - title: Hugo Profile
      #   content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
      #   image: /images/projects/profile.png
      #   featured:
      #     name: Demo
      #     link: https://hugo-profile.netlify.app
      #   # badges:
      #   #   - "Hugo"
      #   #   - "Bootstrap"
      #   #   - "Javascript"
      #   links:
      #     - icon: fa fa-envelope
      #       url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
      #     - icon: fab fa-github
      #       url: https://github.com/gurusabarish/hugo-profile
      #     - icon: fab fa-twitter
      #       url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Predicting centuries in cricket
        content: How to beat Sachin's record of 100 100s!? 
        image: /images/projects/cricket1.jpg
        featured:
          name: Open
          link: https://vra-ml.netlify.app/blogs/centuries
        badges:
          - "Machine Learning"
          - "Regression"
          - "Multiple Linear Regression"
          - "Support Vector Regression"
          - "Decision Tree regression"
          - "Random Forest Regression"
        links:
          - icon: fab fa-github
            url: https://github.com/Vadiraj-13/Predicting-centuries-in-cricket/

      - title: Bank Marketing Campaign
        content: How to store and process data in a distributed way so that it can be used for marketing campaign by a bank? 
        image: /images/projects/bank.png
        featured:
          name: Open
          link: https://vra-ml.netlify.app/blogs/bankcampaign
        badges:
          - "Hadoop"
          - "Spark"
          - "Hive"
          - "Dataproc"
        links:
          - icon: fab fa-github
            url: https://github.com/Vadiraj-13/bank-campaign      




      - title: Exploratory Data Analysis on housing data
        content: In which Indian city, the flats are most expensive?
        image: /images/projects/real-estate.jpg
        featured:
          name: Open
          link: https://vra-ml.netlify.app/blogs/housingEDA/
        badges:
          - "Data Wrangling"
          - "Data Analysis"
          - "Data Visualisation"
          - "Feature Engineering"
          - "Pandas"
          - "Seaborn"
          - "Matplotlib"
        links:
          - icon: fab fa-github
            url: https://github.com/Vadiraj-13/housing-EDA
      
        
      - title: Tic Tac Toe
        content: The infamous tic tac toe game built using Python!
        image: /images/projects/a2.jpg
        featured:
          name: Open
          link: https://vra-ml.netlify.app/blogs/tic_tac_toe/
        badges:
          - "Python"
          - "Interactive Game"
          - "Jupyter Notebook"
        links:
          - icon: fab fa-github
          - url: https://github.com/Vadiraj-13/Tic-tac-toe-Python-project

      - title: Virtual Reality Lab
        content: Can remote lab learning experience be enhanced using Virtual Reality? 
        image: /images/projects/bg.jpg
        featured:
          #name: Demo
          #link: https://vadiraj-13.github.io/lab-in-vr.github.io/
          name: Open
          link: https://vra-ml.netlify.app/blogs/vrblog/
        badges:
          - "Virtual Reality"
          - "Remote Learning"
          - "Animation"
          - "Digital Electronics"


      - title: MSL 2.0
        content: 
        image: /images/projects/msl.jpg
        featured:
          name: Open
          link: https://vra-ml.netlify.app/blogs/msl/
        badges:
          - "Hardware Project"
          - "Automation"
          - "PIR sensor"

      - title: Servo Robotic Arm
        content: A robotic arm with precise angular displacement that can be used in multiple industrial applications like welding, surgery etc.
        image: /images/projects/ra.jpg
        featured:
          name: Open
          link: https://vra-ml.netlify.app/blogs/ra/
        badges:
          - "Robotic Arm"
          - "Servo Motor"

      # - title: Hugo Profile V2
      #   content: A clean and simple Hugo template for personal portfolio and blog.
      #   image: /images/projects/profile2.jpg
      #   featured:
      #     name: Demo V2
      #     link: https://hugo-profile-2.netlify.app
      #   badges:
      #     - "Hugo"
      #     - "Bootstrap"
      #     - "Javascript"
      #   links:
      #     - icon: fab fa-github
      #       url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: vadiraj66@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      #github: https://github.com
      linkedin: https://linkedin.com
      #twitter: https://twitter.com
      #instagram: https://instagram.com
      #facebook: https://facebook.com
